#!/usr/bin/env bash
# worktree-spawn.sh — spawn a git worktree following MASTERMIND 2.0 conventions.
#
# Usage:
#   bash scripts/worktree-spawn.sh <slug> [--type feat|fix|chore|refactor|docs|test|perf|exp] [--base origin/main] [--install-deps]
#
# Convention:
#   Location: ../<repo>-worktrees/<slug>
#   Branch:   <type>/<slug>   (default type: feat)
#   Port offset: deterministic 4-digit offset derived from SHA-256 of the slug (10000..19999)
#
# See .cursor/rules/07-subagent-orchestration.mdc §Parallel execution with Git worktrees.

set -euo pipefail

SLUG=""
TYPE="feat"
BASE="origin/main"
INSTALL_DEPS=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --type)         TYPE="${2:-feat}"; shift 2 ;;
    --base)         BASE="${2:-origin/main}"; shift 2 ;;
    --install-deps) INSTALL_DEPS=1; shift ;;
    -h|--help)      sed -n '2,18p' "$0"; exit 0 ;;
    *)
      if [[ -z "$SLUG" ]]; then SLUG="$1"; shift
      else echo "Unknown arg: $1" >&2; exit 2; fi
      ;;
  esac
done

if [[ -z "$SLUG" ]]; then
  echo "ERROR: slug required. Usage: worktree-spawn.sh <slug> [--type ...] [--base ...] [--install-deps]" >&2
  exit 2
fi
if ! [[ "$SLUG" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
  echo "ERROR: slug must be kebab-case (lowercase letters, digits, hyphens). Got: $SLUG" >&2
  exit 2
fi
case "$TYPE" in
  feat|fix|chore|refactor|docs|test|perf|exp) ;;
  *) echo "ERROR: type must be one of feat|fix|chore|refactor|docs|test|perf|exp" >&2; exit 2 ;;
esac

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
REPO_NAME="$( basename "$REPO_ROOT" )"

WORKTREES_ROOT="$( dirname "$REPO_ROOT" )/${REPO_NAME}-worktrees"
WORKTREE_PATH="$WORKTREES_ROOT/$SLUG"
BRANCH="${TYPE}/${SLUG}"

# Deterministic port offset from SHA-256 of slug (first 2 bytes → 0..65535 → mod 10000 → + 10000)
if command -v sha256sum >/dev/null 2>&1; then
  HASH_HEX=$(printf %s "$SLUG" | sha256sum | awk '{print $1}')
elif command -v shasum >/dev/null 2>&1; then
  HASH_HEX=$(printf %s "$SLUG" | shasum -a 256 | awk '{print $1}')
else
  echo "ERROR: need sha256sum or shasum in PATH" >&2
  exit 2
fi
NUM_HEX="${HASH_HEX:0:4}"
NUM_DEC=$(( 16#${NUM_HEX} % 10000 ))
PORT_OFFSET=$(( 10000 + NUM_DEC ))

echo ""
echo "=== worktree-spawn ==="
echo "Repo:         $REPO_ROOT"
echo "Slug:         $SLUG"
echo "Branch:       $BRANCH"
echo "Base branch:  $BASE"
echo "Worktree:     $WORKTREE_PATH"
echo "Port offset:  $PORT_OFFSET  (dev at $((3000+PORT_OFFSET)), db at $((5432+PORT_OFFSET)))"
echo ""

cd "$REPO_ROOT"

mkdir -p "$WORKTREES_ROOT"

git worktree prune >/dev/null 2>&1 || true

if [[ -d "$WORKTREE_PATH" ]]; then
  echo "Worktree already exists at $WORKTREE_PATH — re-using."
else
  if ! git show-ref --verify --quiet "refs/remotes/$BASE" \
       && ! git show-ref --verify --quiet "refs/heads/$BASE"; then
    echo "Base branch $BASE not found locally. Running 'git fetch --all' ..."
    git fetch --all --quiet
  fi
  git worktree add -b "$BRANCH" "$WORKTREE_PATH" "$BASE"
fi

cat > "$WORKTREE_PATH/.worktree-env" <<EOF
# Auto-generated by scripts/worktree-spawn.sh
# Derived from slug: $SLUG
MM_WORKTREE_SLUG=$SLUG
MM_PORT_OFFSET=$PORT_OFFSET
MM_DEV_PORT=$((3000+PORT_OFFSET))
MM_DB_PORT=$((5432+PORT_OFFSET))
EOF

echo "Wrote $WORKTREE_PATH/.worktree-env (source it from your dev server startup)."

if [[ $INSTALL_DEPS -eq 1 ]]; then
  echo ""
  echo "Installing dependencies (best-effort) ..."
  (
    cd "$WORKTREE_PATH"
    if   [[ -f pnpm-lock.yaml ]]; then pnpm install --prefer-offline
    elif [[ -f package-lock.json ]]; then npm ci --prefer-offline
    elif [[ -f yarn.lock ]]; then yarn install --prefer-offline
    elif [[ -f package.json ]]; then npm install --prefer-offline
    elif [[ -f pyproject.toml ]]; then
      if command -v uv >/dev/null 2>&1; then uv sync
      elif command -v poetry >/dev/null 2>&1; then poetry install
      fi
    else
      echo "No recognized lockfile. Skipping."
    fi
  )
fi

echo ""
echo "Ready. cd into the worktree:"
echo "   cd \"$WORKTREE_PATH\""
echo ""
echo "When done: bash scripts/worktree-cleanup.sh --slug $SLUG"
