<#
.SYNOPSIS
    Spawn a new git worktree following the MASTERMIND 2.0 conventions. Creates a sibling folder, checks out a new branch, assigns a deterministic port offset, and optionally installs dependencies.

.DESCRIPTION
    Convention:
      - Location: ../<repo>-worktrees/<slug>
      - Branch:   feat/<slug>  (or any of: fix/ chore/ refactor/ docs/ test/ perf/ exp/)
      - Port offset: deterministic 4-digit offset derived from SHA-256 of the slug (range 10000-19999)
      - All worktrees start from the same commit (default: origin/main)
      - Idempotent: if the worktree already exists, the script re-enters it and prints status.

    The port offset lets you run multiple dev servers in parallel without collisions:
      dev server:   http://localhost:3000 + PORT_OFFSET
      db:           postgres on 5432 + PORT_OFFSET

    See .cursor/rules/07-subagent-orchestration.mdc §Parallel execution with Git worktrees.

.PARAMETER Slug
    Short kebab-case identifier. Used for the branch and folder name.

.PARAMETER Type
    Branch prefix. One of: feat, fix, chore, refactor, docs, test, perf, exp.
    Defaults to 'feat'.

.PARAMETER BaseBranch
    Base branch to fork from. Defaults to 'origin/main'.

.PARAMETER InstallDeps
    If present, runs the stack's dependency install (best-effort: npm / pnpm / yarn / pip).

.EXAMPLE
    pwsh -File scripts/worktree-spawn.ps1 -Slug auth-refactor
    pwsh -File scripts/worktree-spawn.ps1 -Slug magic-link-signup -Type feat -InstallDeps
    pwsh -File scripts/worktree-spawn.ps1 -Slug stripe-webhook-fix -Type fix
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$Slug,
    [ValidateSet('feat','fix','chore','refactor','docs','test','perf','exp')]
    [string]$Type = 'feat',
    [string]$BaseBranch = 'origin/main',
    [switch]$InstallDeps
)

$ErrorActionPreference = 'Stop'

# Validate slug
if ($Slug -notmatch '^[a-z0-9]+(-[a-z0-9]+)*$') {
    Write-Error "Slug must be kebab-case (lowercase letters, digits, hyphens, no leading/trailing hyphen). Got: '$Slug'"
    exit 1
}

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$repoName = Split-Path -Leaf $repoRoot

# Layout: ../<repoName>-worktrees/<slug>
$worktreesRoot = Join-Path (Split-Path -Parent $repoRoot) "$repoName-worktrees"
$worktreePath  = Join-Path $worktreesRoot $Slug
$branch = "$Type/$Slug"

# Deterministic port offset from SHA-256 of the slug - stable across machines
$hashBytes = [System.Security.Cryptography.SHA256]::Create().ComputeHash([System.Text.Encoding]::UTF8.GetBytes($Slug))
$num = [int]([System.BitConverter]::ToUInt16($hashBytes, 0) % 10000)
$portOffset = 10000 + $num   # 10000..19999

Write-Host ""
Write-Host "=== worktree-spawn ==="
Write-Host "Repo:         $repoRoot"
Write-Host "Slug:         $Slug"
Write-Host "Branch:       $branch"
Write-Host "Base branch:  $BaseBranch"
Write-Host "Worktree:     $worktreePath"
Write-Host "Port offset:  $portOffset  (dev at $(3000 + $portOffset), db at $(5432 + $portOffset))"
Write-Host ""

Push-Location $repoRoot
try {
    if (-not (Test-Path $worktreesRoot)) {
        New-Item -ItemType Directory -Path $worktreesRoot | Out-Null
    }

    # Clean stale metadata before attempting to create
    git worktree prune 2>&1 | Out-Null

    if (Test-Path $worktreePath) {
        Write-Host "Worktree already exists at $worktreePath - re-using." -ForegroundColor Yellow
    } else {
        # Make sure the base branch is reachable locally
        $baseExists = (git show-ref --verify --quiet "refs/remotes/$BaseBranch"; $LASTEXITCODE -eq 0) -or `
                      (git show-ref --verify --quiet "refs/heads/$BaseBranch"; $LASTEXITCODE -eq 0)
        if (-not $baseExists) {
            Write-Host "Base branch $BaseBranch not found locally. Running 'git fetch --all' ..." -ForegroundColor Yellow
            git fetch --all --quiet
        }

        git worktree add -b $branch $worktreePath $BaseBranch 2>&1 | Out-Host
        if ($LASTEXITCODE -ne 0) {
            Write-Error "git worktree add failed."
            exit 1
        }
    }

    # Write a small .worktree-env file for dev servers to consume
    $envFile = Join-Path $worktreePath '.worktree-env'
    @"
# Auto-generated by scripts/worktree-spawn.ps1
# Derived from slug: $Slug
MM_WORKTREE_SLUG=$Slug
MM_PORT_OFFSET=$portOffset
MM_DEV_PORT=$(3000 + $portOffset)
MM_DB_PORT=$(5432 + $portOffset)
"@ | Set-Content -Encoding UTF8 -Path $envFile

    Write-Host "Wrote $envFile (source it from your dev server startup)."

    if ($InstallDeps) {
        Write-Host ""
        Write-Host "Installing dependencies (best-effort) ..."
        Push-Location $worktreePath
        try {
            if (Test-Path 'pnpm-lock.yaml') { pnpm install --prefer-offline }
            elseif (Test-Path 'package-lock.json') { npm ci --prefer-offline }
            elseif (Test-Path 'yarn.lock') { yarn install --prefer-offline }
            elseif (Test-Path 'package.json') { npm install --prefer-offline }
            elseif (Test-Path 'pyproject.toml') {
                if (Get-Command uv -ErrorAction SilentlyContinue) { uv sync }
                elseif (Get-Command poetry -ErrorAction SilentlyContinue) { poetry install }
            }
            else { Write-Host "No recognized lockfile. Skipping." }
        } finally {
            Pop-Location
        }
    }

    Write-Host ""
    Write-Host "Ready. cd into the worktree:" -ForegroundColor Green
    Write-Host "   cd `"$worktreePath`""
    Write-Host ""
    Write-Host "When done: pwsh -File scripts/worktree-cleanup.ps1 -Slug $Slug"
    exit 0
}
finally {
    Pop-Location
}
